// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
<<<<<<< Updated upstream
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
=======
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
//import 'package:flutter/foundation.dart'
//    show defaultTargetPlatform, kIsWeb, TargetPlatform;
>>>>>>> Stashed changes

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

<<<<<<< Updated upstream
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHN-L5JGi1_nweqfpRXMRV0vzbzySJ4bs',
    appId: '1:926744933692:web:d3a72a97b8da20f9d8da39',
    messagingSenderId: '926744933692',
    projectId: 'testdb-a0979',
    authDomain: 'testdb-a0979.firebaseapp.com',
    storageBucket: 'testdb-a0979.appspot.com',
    measurementId: 'G-XLMQ1R1VBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfiDhcUrpk5V81KAivlgdPD5eNYX5_5QA',
    appId: '1:926744933692:android:375c27885712e18ed8da39',
    messagingSenderId: '926744933692',
    projectId: 'testdb-a0979',
    storageBucket: 'testdb-a0979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7IVBWm6OtiY2KpQ53WutX88aqKp5QbNw',
    appId: '1:926744933692:ios:33957fae357f3611d8da39',
    messagingSenderId: '926744933692',
    projectId: 'testdb-a0979',
    storageBucket: 'testdb-a0979.appspot.com',
    iosClientId:
        '926744933692-2rdh0ddtp7a8jkebp74r4rqbtk35ea62.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7IVBWm6OtiY2KpQ53WutX88aqKp5QbNw',
    appId: '1:926744933692:ios:33957fae357f3611d8da39',
    messagingSenderId: '926744933692',
    projectId: 'testdb-a0979',
    storageBucket: 'testdb-a0979.appspot.com',
    iosClientId:
        '926744933692-2rdh0ddtp7a8jkebp74r4rqbtk35ea62.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoBank',
  );
}
=======
//class DefaultFirebaseOptions {
//  static FirebaseOptions get currentPlatform {
//    if (kIsWeb) {
//      return web;
//    }
//    switch (defaultTargetPlatform) {
//      case TargetPlatform.android:
//        return android;
//      case TargetPlatform.iOS:
//        return ios;
//      case TargetPlatform.macOS:
//        return macos;
//      case TargetPlatform.windows:
//        throw UnsupportedError(
//          'DefaultFirebaseOptions have not been configured for windows - '
//          'you can reconfigure this by running the FlutterFire CLI again.',
//        );
//      case TargetPlatform.linux:
//        throw UnsupportedError(
//          'DefaultFirebaseOptions have not been configured for linux - '
//          'you can reconfigure this by running the FlutterFire CLI again.',
//        );
//      default:
//        throw UnsupportedError(
//          'DefaultFirebaseOptions are not supported for this platform.',
//        );
//    }
//  }

//  static const FirebaseOptions web = FirebaseOptions(
//    apiKey: 'AIzaSyCHN-L5JGi1_nweqfpRXMRV0vzbzySJ4bs',
//    appId: '1:926744933692:web:d3a72a97b8da20f9d8da39',
//    messagingSenderId: '926744933692',
//    projectId: 'testdb-a0979',
//    authDomain: 'testdb-a0979.firebaseapp.com',
//    storageBucket: 'testdb-a0979.appspot.com',
//    measurementId: 'G-XLMQ1R1VBD',
//  );

//  static const FirebaseOptions android = FirebaseOptions(
//    apiKey: 'AIzaSyAfiDhcUrpk5V81KAivlgdPD5eNYX5_5QA',
//    appId: '1:926744933692:android:375c27885712e18ed8da39',
//    messagingSenderId: '926744933692',
//    projectId: 'testdb-a0979',
//    storageBucket: 'testdb-a0979.appspot.com',
//  );

//  static const FirebaseOptions ios = FirebaseOptions(
//    apiKey: 'AIzaSyA7IVBWm6OtiY2KpQ53WutX88aqKp5QbNw',
//    appId: '1:926744933692:ios:33957fae357f3611d8da39',
//    messagingSenderId: '926744933692',
//    projectId: 'testdb-a0979',
//    storageBucket: 'testdb-a0979.appspot.com',
//    iosClientId:
//        '926744933692-2rdh0ddtp7a8jkebp74r4rqbtk35ea62.apps.googleusercontent.com',
//    iosBundleId: 'com.example.infoBank',
//  );

//  static const FirebaseOptions macos = FirebaseOptions(
//    apiKey: 'AIzaSyA7IVBWm6OtiY2KpQ53WutX88aqKp5QbNw',
//    appId: '1:926744933692:ios:33957fae357f3611d8da39',
//    messagingSenderId: '926744933692',
//    projectId: 'testdb-a0979',
//    storageBucket: 'testdb-a0979.appspot.com',
//    iosClientId:
//        '926744933692-2rdh0ddtp7a8jkebp74r4rqbtk35ea62.apps.googleusercontent.com',
//    iosBundleId: 'com.example.infoBank',
//  );
//}
>>>>>>> Stashed changes
